FROM medicean/vulapps:base_lamp

MAINTAINER mxh <mxh_xxx@yeah.net>

COPY challenges /var/www/html/

WORKDIR /var/www/html

RUN rm -f /var/www/html/phpinfo.php && \
    chmod a+x -R 8f971f70a8d046ab/ && \
    chmod a+x -R d9a92ae7020043e9/ && \
    chmod a+x -R 9763f1b840ce1284/ && \
    chmod a+x -R 46b9a49091a02707/ && \
    chmod a+x -R 12d686301527a029/ && \
    chmod a+x -R 99b202162de3248c/ && \
    chmod a+x -R c28379aac7444db8/ && \
    chmod a+x -R 05627c0806f4eb3b/ && \
    chmod a+x -R d15e7375cb9beb70/ && \
    chmod a+x -R 05fdd60a94ec42f0/ && \
    chmod a+x -R d3b0cbd599d4a232/ && \
    chmod a+x -R 2f2eb0f43f1df420/ && \
    chmod a+x -R c4526884d5721776/ 
