FROM medicean/vulapps:base_lamp

MAINTAINER mxh <mxh_xxx@yeah.net>

COPY abf20c91a442da48 /var/www/html/abf20c91a442da48/

WORKDIR /var/www/html

RUN rm -f /var/www/html/index.html /var/www/html/phpinfo.php

RUN chmod a+x -R abf20c91a442da48/

